// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: modules/facility/proto/facilityPb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message for checking slot availability
type CheckSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	FacilityName  string                 `protobuf:"bytes,2,opt,name=facility_name,json=facilityName,proto3" json:"facility_name,omitempty"`
	SlotType      string                 `protobuf:"bytes,3,opt,name=slot_type,json=slotType,proto3" json:"slot_type,omitempty"` // "normal" or "badminton"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSlotRequest) Reset() {
	*x = CheckSlotRequest{}
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSlotRequest) ProtoMessage() {}

func (x *CheckSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSlotRequest.ProtoReflect.Descriptor instead.
func (*CheckSlotRequest) Descriptor() ([]byte, []int) {
	return file_modules_facility_proto_facilityPb_proto_rawDescGZIP(), []int{0}
}

func (x *CheckSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *CheckSlotRequest) GetFacilityName() string {
	if x != nil {
		return x.FacilityName
	}
	return ""
}

func (x *CheckSlotRequest) GetSlotType() string {
	if x != nil {
		return x.SlotType
	}
	return ""
}

type SlotAvailabilityResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable     bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	CurrentBookings int32                  `protobuf:"varint,2,opt,name=current_bookings,json=currentBookings,proto3" json:"current_bookings,omitempty"`
	MaxBookings     int32                  `protobuf:"varint,3,opt,name=max_bookings,json=maxBookings,proto3" json:"max_bookings,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SlotAvailabilityResponse) Reset() {
	*x = SlotAvailabilityResponse{}
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotAvailabilityResponse) ProtoMessage() {}

func (x *SlotAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*SlotAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_modules_facility_proto_facilityPb_proto_rawDescGZIP(), []int{1}
}

func (x *SlotAvailabilityResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *SlotAvailabilityResponse) GetCurrentBookings() int32 {
	if x != nil {
		return x.CurrentBookings
	}
	return 0
}

func (x *SlotAvailabilityResponse) GetMaxBookings() int32 {
	if x != nil {
		return x.MaxBookings
	}
	return 0
}

func (x *SlotAvailabilityResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Message for getting facility price
type FacilityPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FacilityName  string                 `protobuf:"bytes,1,opt,name=facility_name,json=facilityName,proto3" json:"facility_name,omitempty"`
	UserType      string                 `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"` // "insider" or "outsider"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacilityPriceRequest) Reset() {
	*x = FacilityPriceRequest{}
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacilityPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacilityPriceRequest) ProtoMessage() {}

func (x *FacilityPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacilityPriceRequest.ProtoReflect.Descriptor instead.
func (*FacilityPriceRequest) Descriptor() ([]byte, []int) {
	return file_modules_facility_proto_facilityPb_proto_rawDescGZIP(), []int{2}
}

func (x *FacilityPriceRequest) GetFacilityName() string {
	if x != nil {
		return x.FacilityName
	}
	return ""
}

func (x *FacilityPriceRequest) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

type FacilityPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacilityPriceResponse) Reset() {
	*x = FacilityPriceResponse{}
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacilityPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacilityPriceResponse) ProtoMessage() {}

func (x *FacilityPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacilityPriceResponse.ProtoReflect.Descriptor instead.
func (*FacilityPriceResponse) Descriptor() ([]byte, []int) {
	return file_modules_facility_proto_facilityPb_proto_rawDescGZIP(), []int{3}
}

func (x *FacilityPriceResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FacilityPriceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FacilityPriceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Message for updating slot booking count
type UpdateSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	FacilityName  string                 `protobuf:"bytes,2,opt,name=facility_name,json=facilityName,proto3" json:"facility_name,omitempty"`
	Increment     int32                  `protobuf:"varint,3,opt,name=increment,proto3" json:"increment,omitempty"` // Can be positive or negative
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSlotRequest) Reset() {
	*x = UpdateSlotRequest{}
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSlotRequest) ProtoMessage() {}

func (x *UpdateSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSlotRequest.ProtoReflect.Descriptor instead.
func (*UpdateSlotRequest) Descriptor() ([]byte, []int) {
	return file_modules_facility_proto_facilityPb_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *UpdateSlotRequest) GetFacilityName() string {
	if x != nil {
		return x.FacilityName
	}
	return ""
}

func (x *UpdateSlotRequest) GetIncrement() int32 {
	if x != nil {
		return x.Increment
	}
	return 0
}

type UpdateSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSlotResponse) Reset() {
	*x = UpdateSlotResponse{}
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSlotResponse) ProtoMessage() {}

func (x *UpdateSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_facility_proto_facilityPb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSlotResponse.ProtoReflect.Descriptor instead.
func (*UpdateSlotResponse) Descriptor() ([]byte, []int) {
	return file_modules_facility_proto_facilityPb_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSlotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSlotResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_modules_facility_proto_facilityPb_proto protoreflect.FileDescriptor

const file_modules_facility_proto_facilityPb_proto_rawDesc = "" +
	"\n" +
	"'modules/facility/proto/facilityPb.proto\x12\bfacility\"m\n" +
	"\x10CheckSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12#\n" +
	"\rfacility_name\x18\x02 \x01(\tR\ffacilityName\x12\x1b\n" +
	"\tslot_type\x18\x03 \x01(\tR\bslotType\"\xb0\x01\n" +
	"\x18SlotAvailabilityResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\x12)\n" +
	"\x10current_bookings\x18\x02 \x01(\x05R\x0fcurrentBookings\x12!\n" +
	"\fmax_bookings\x18\x03 \x01(\x05R\vmaxBookings\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"X\n" +
	"\x14FacilityPriceRequest\x12#\n" +
	"\rfacility_name\x18\x01 \x01(\tR\ffacilityName\x12\x1b\n" +
	"\tuser_type\x18\x02 \x01(\tR\buserType\"n\n" +
	"\x15FacilityPriceResponse\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"o\n" +
	"\x11UpdateSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12#\n" +
	"\rfacility_name\x18\x02 \x01(\tR\ffacilityName\x12\x1c\n" +
	"\tincrement\x18\x03 \x01(\x05R\tincrement\"S\n" +
	"\x12UpdateSlotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\x94\x02\n" +
	"\x0fFacilityService\x12W\n" +
	"\x15CheckSlotAvailability\x12\x1a.facility.CheckSlotRequest\x1a\".facility.SlotAvailabilityResponse\x12S\n" +
	"\x10GetFacilityPrice\x12\x1e.facility.FacilityPriceRequest\x1a\x1f.facility.FacilityPriceResponse\x12S\n" +
	"\x16UpdateSlotBookingCount\x12\x1b.facility.UpdateSlotRequest\x1a\x1c.facility.UpdateSlotResponseB9Z7github.com/Sport-Complex/backend/modules/facility/protob\x06proto3"

var (
	file_modules_facility_proto_facilityPb_proto_rawDescOnce sync.Once
	file_modules_facility_proto_facilityPb_proto_rawDescData []byte
)

func file_modules_facility_proto_facilityPb_proto_rawDescGZIP() []byte {
	file_modules_facility_proto_facilityPb_proto_rawDescOnce.Do(func() {
		file_modules_facility_proto_facilityPb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_facility_proto_facilityPb_proto_rawDesc), len(file_modules_facility_proto_facilityPb_proto_rawDesc)))
	})
	return file_modules_facility_proto_facilityPb_proto_rawDescData
}

var file_modules_facility_proto_facilityPb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_modules_facility_proto_facilityPb_proto_goTypes = []any{
	(*CheckSlotRequest)(nil),         // 0: facility.CheckSlotRequest
	(*SlotAvailabilityResponse)(nil), // 1: facility.SlotAvailabilityResponse
	(*FacilityPriceRequest)(nil),     // 2: facility.FacilityPriceRequest
	(*FacilityPriceResponse)(nil),    // 3: facility.FacilityPriceResponse
	(*UpdateSlotRequest)(nil),        // 4: facility.UpdateSlotRequest
	(*UpdateSlotResponse)(nil),       // 5: facility.UpdateSlotResponse
}
var file_modules_facility_proto_facilityPb_proto_depIdxs = []int32{
	0, // 0: facility.FacilityService.CheckSlotAvailability:input_type -> facility.CheckSlotRequest
	2, // 1: facility.FacilityService.GetFacilityPrice:input_type -> facility.FacilityPriceRequest
	4, // 2: facility.FacilityService.UpdateSlotBookingCount:input_type -> facility.UpdateSlotRequest
	1, // 3: facility.FacilityService.CheckSlotAvailability:output_type -> facility.SlotAvailabilityResponse
	3, // 4: facility.FacilityService.GetFacilityPrice:output_type -> facility.FacilityPriceResponse
	5, // 5: facility.FacilityService.UpdateSlotBookingCount:output_type -> facility.UpdateSlotResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_facility_proto_facilityPb_proto_init() }
func file_modules_facility_proto_facilityPb_proto_init() {
	if File_modules_facility_proto_facilityPb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_facility_proto_facilityPb_proto_rawDesc), len(file_modules_facility_proto_facilityPb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_facility_proto_facilityPb_proto_goTypes,
		DependencyIndexes: file_modules_facility_proto_facilityPb_proto_depIdxs,
		MessageInfos:      file_modules_facility_proto_facilityPb_proto_msgTypes,
	}.Build()
	File_modules_facility_proto_facilityPb_proto = out.File
	file_modules_facility_proto_facilityPb_proto_goTypes = nil
	file_modules_facility_proto_facilityPb_proto_depIdxs = nil
}
