name: Update Contributor Stats

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Generate Contribution Stats
        run: |
          echo "## Contributors" > temp_stats.md
          echo "" >> temp_stats.md
          echo "### Team Members and Contributions" >> temp_stats.md
          echo "" >> temp_stats.md
          
          # 6531503042 - Nimit
          COMMITS_1=$(git log --author="6531503042" --oneline | wc -l)
          echo "#### 6531503042 - Nimit Tanboontor (@6531503042)" >> temp_stats.md
          echo "![Contributions](https://img.shields.io/badge/Commits-$COMMITS_1-blue)" >> temp_stats.md
          echo "Recent contributions:" >> temp_stats.md
          git log --author="6531503042" --pretty=format:"- %s" -n 5 >> temp_stats.md
          echo "" >> temp_stats.md
          echo "" >> temp_stats.md
          
          # 6531503024 - Thanaphat
          COMMITS_2=$(git log --author="thanaphat43" --oneline | wc -l)
          echo "#### 6531503024 - Thanaphat Thammasen (@thanaphat43)" >> temp_stats.md
          echo "![Contributions](https://img.shields.io/badge/Commits-$COMMITS_2-blue)" >> temp_stats.md
          echo "Recent contributions:" >> temp_stats.md
          git log --author="thanaphat43" --pretty=format:"- %s" -n 5 >> temp_stats.md
          echo "" >> temp_stats.md
          echo "" >> temp_stats.md
          
          # 6531503048 - Peeranat
          COMMITS_3=$(git log --author="peeranat45" --oneline | wc -l)
          echo "#### 6531503048 - Peeranat Patarakittisopol (@peeranat45)" >> temp_stats.md
          echo "![Contributions](https://img.shields.io/badge/Commits-$COMMITS_3-blue)" >> temp_stats.md
          echo "Recent contributions:" >> temp_stats.md
          git log --author="peeranat45" --pretty=format:"- %s" -n 5 >> temp_stats.md
          echo "" >> temp_stats.md
          
          echo "" >> temp_stats.md
          echo "Last updated: $(date)" >> temp_stats.md
          echo "" >> temp_stats.md
          echo "View detailed contribution statistics: [Contributors Graph](https://github.com/6531503042/Sport-Complex/graphs/contributors)" >> temp_stats.md

      - name: Update README
        run: |
          # Get everything before ## Contributors
          sed '/^## Contributors/q' README.md > new_readme.md
          # Add the new stats
          cat temp_stats.md >> new_readme.md
          # Move the new README into place
          mv new_readme.md README.md

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "docs: Update contributor stats" || exit 0
          git push